### ISSUE TITLE
Remove hyphen 

### ISSUE THREAD

**Issue by hasibzunair** [tajwarabraraleef/3Dpix2pix-for-prostate-brachytherapy#1]
Title should be "Automatic-Seed-planning-for-prostate-brachytherapy" instead of "Automatic-Seed-planning-for-prostate-brachytherapy-".

OCD is kicking in. Fix it or I can send a PR.

**Comment by hasibzunair** [comment]
@tajwarabraraleef kire code toh nai paper er

**Comment by tajwarabraraleef** [comment]
@hasibzunair tk dao tarpor dibo
